### ISSUE TITLE
Unable to install on Windows. 

### ISSUE THREAD

**Issue by harrisonhjones** [adriancooney/tw#1]
I tried installing this on a x64 windows box today. It first balked on some chmod error (error 1 below) and then, after downloading the repo, unzipping, it wanted eslint to be installed. After I installed eslint it had yet another error (error 2) which I couldn't get past. Any ideas?

Error 1:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tw-beta"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\Harrison\AppData\Roaming\npm\node_modules\tw-beta\bin\tw
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, chmod 'C:\Users\Harrison\AppData\Roaming\npm\node_module
s\tw-beta\bin\tw'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Harrison\Downloads\tw-master\tw-master\npm-debug.log
```

Error 2:

> tw-beta@0.2.0 prepublish C:\Users\Harrison\Downloads\tw-master\tw-master
>     > npm run build

```
\
> tw-beta@0.2.0 build C:\Users\Harrison\Downloads\tw-master\tw-master
> npm run lint && npm run clean && npm run build:src && npm run build:bin

|
> tw-beta@0.2.0 lint C:\Users\Harrison\Downloads\tw-master\tw-master
> npm run lint:bin && npm run lint:src

|
> tw-beta@0.2.0 lint:bin C:\Users\Harrison\Downloads\tw-master\tw-master
> eslint bin/tw*

fs.js:797
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\Users\Harrison\Downloads\tw-master\
tw-master\bin\tw*'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at walk (C:\Users\Harrison\AppData\Roaming\npm\node_modules\eslint\lib\util\
traverse.js:36:15)
    at C:\Users\Harrison\AppData\Roaming\npm\node_modules\eslint\lib\util\traver
se.js:104:9
    at Array.forEach (native)
    at traverse (C:\Users\Harrison\AppData\Roaming\npm\node_modules\eslint\lib\u
til\traverse.js:103:11)
    at CLIEngine.executeOnFiles (C:\Users\Harrison\AppData\Roaming\npm\node_modu
les\eslint\lib\cli-engine.js:382:9)
    at Object.cli.execute (C:\Users\Harrison\AppData\Roaming\npm\node_modules\es
lint\lib\cli.js:147:95)
    at Object.<anonymous> (C:\Users\Harrison\AppData\Roaming\npm\node_modules\es
lint\bin\eslint.js:32:20)
    at Module._compile (module.js:460:26)
/
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint:bin"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! tw-beta@0.2.0 lint:bin: `eslint bin/tw*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tw-beta@0.2.0 lint:bin script 'eslint bin/tw*'.
npm ERR! This is most likely a problem with the tw-beta package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint bin/tw*
npm ERR! You can get their info via:
npm ERR!     npm owner ls tw-beta
npm ERR! There is likely additional logging output above.
```

**Comment by adriancooney** [comment]
Thanks for giving `tw-beta` a shot! Sorry for the problems, the tool _is very_ early stages and I haven't had a chance to fully test in Windows yet. I just pushed some code there so that the build process is more resistant to cross platform issues. Could you give building it a shot again? (Make sure you run `npm install` before hand in the root directory of the projects to install all the dependencies). Thanks again!

**Comment by harrisonhjones** [comment]
Thanks Adrian! I got much further this time. New error below. I looked into fixing this myself but I was unsuccessful. Not too familiar with eslint. 

```
> eslint src --ignore-pattern src/parser/TeamworkParser.js


src\action\index.js
  1:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\action\LogAction.js
  1:42  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\library\Action.js
  1:45  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\library\Config.js
  1:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\library\Debug.js
  1:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\library\Model.js
  1:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Company.js
  1:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\index.js
  1:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Installation.js
  1:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Log.js
  1:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Person.js
  1:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Project.js
  1:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Tag.js
  1:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Task.js
  1:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\model\Tasklist.js
  1:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\reporter\default.js
  1:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\Teamwork.js
  1:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\TeamworkAPI.js
  1:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

src\TeamworkCLI.js
  1:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

? 19 problems (19 errors, 0 warnings)
```

**Comment by adriancooney** [comment]
Oh, very interesting. Looks like the linter is throwing errors for Windows style line breaks. I removed the rule forcing Unix style line endings. Give it another go with the latest if you can please, thanks!

**Comment by harrisonhjones** [comment]
Got past it by altering git to stop autoconverting `LF` to `CRLF` and it got to this next fun error :) I do appreciate the help!

```
> tw-beta@0.2.0 build:bin:compile C:\Users\hhjones\Documents\VersionControl\Amaz
on\TW-CLI
> babel 'bin/tw*' -d build

'bin/tw*' doesn't exist

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:bin:compile"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! tw-beta@0.2.0 build:bin:compile: `babel 'bin/tw*' -d build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the tw-beta@0.2.0 build:bin:compile script 'babel 'bin/tw*' -
d build'.
npm ERR! This is most likely a problem with the tw-beta package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel 'bin/tw*' -d build
npm ERR! You can get their info via:
npm ERR!     npm owner ls tw-beta
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hhjones\Documents\VersionControl\Amazon\TW-CLI\npm-debug.l
og
```

**Comment by adriancooney** [comment]
Ah, this is a little bit of a pickle. I should probably introduce an actual build system. Windows doesn't seem to accept globs and Babel can compile directories but not files without extensions. Our only hope is that Babel itself takes glob and sorts it. Could you give the latest a shot?

**Comment by harrisonhjones** [comment]
New exciting error! 

```
> tw-beta@0.2.0 build:bin:rename C:\Users\hhjones\Documents\VersionControl\Amazo
n\TW-CLI
> renamer -f '.js' -r '' 'build/bin/*.js' -v

x 'build\bin\*.js' (does not exist)

> tw-beta@0.2.0 build:bin:fix-binary C:\Users\hhjones\Documents\VersionControl\A
mazon\TW-CLI
> replace '#!/usr/bin/env babel-node --' '#!/usr/bin/env node' build/bin -r

fs.js:792
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\Users\hhjones\Documents\VersionCont
rol\Amazon\TW-CLI\node''
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at replacizeFileSync (C:\Users\hhjones\Documents\VersionControl\Amazon\TW-CL
I\node_modules\replace\replace.js:121:22)
    at module.exports (C:\Users\hhjones\Documents\VersionControl\Amazon\TW-CLI\n
ode_modules\replace\replace.js:64:13)
    at Object.<anonymous> (C:\Users\hhjones\Documents\VersionControl\Amazon\TW-C
LI\node_modules\replace\bin\replace.js:57:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Progress!

**Comment by adriancooney** [comment]
Oh interesting. Getting there. I think we need to replace all the single
quote with double quotes in the scripts object in the package.json file.
I'm AFK at the minute if you'd like to give it a shot yourself, it'd be
much appreciated. Thanks for all this testing by the way!

**Comment by harrisonhjones** [comment]
It appears the fix was the opposite. I had to chage some single quotes to double quotes. 

`npm install` works! but I'm not sure how to run it after that :/ however `npm install -g` results in the error I posted in the PR
